on:
  push:
    branches:
      - "main"
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy News
    env:
      JBANG_REPO: "/home/runner/.jbang/repository"
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: /home/runner/.jbang
        key: ${{ runner.os }}-jbang
    - uses: actions/setup-java@v3
      with:
        distribution: 'adopt' # See 'Supported distributions' for available options
        java-version: '17'
    - name: Install JBang
      shell: bash
      run: |
        echo "HOME: $HOME"
        echo "JBANG_REPO: $JBANG_REPO"
        if [ ! -x "/home/runner/.jbang/bin/jbang" ]; then
          curl -Ls https://sh.jbang.dev | bash -s - app setup
        fi
    - name: Build and Deploy to GH Pages
      shell: bash
      run: |
        ./deploy.sh
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
