on:
  push:
    branches:
      - "main"
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
    
jobs:
  jbang:
    runs-on: ubuntu-latest
    name: Run Script
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: /root/.jbang
        key: $-jbang-$
        restore-keys: |
            $-jbang-
    - uses: actions/setup-java@v3
      with:
        distribution: 'adopt' # See 'Supported distributions' for available options
        java-version: '17'
    - name: Install JBang
      shell: bash
      run: |
        curl -Ls https://sh.jbang.dev | bash -s - app setup
    - name: Build script
      run: |
        ~/.jbang/bin/jbang build generate.kt
    - name: Build and Deploy to GH Pages
      shell: bash
      run: |
        ./deploy.sh
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
