name: deploy
on:
  workflow_dispatch:
    inputs:
      ref_to_publish:
        description: 'Ref (branch or tag)'
        required: true
        default: 'refs/heads/main'
  release:
    types: [released]

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          make build

      - name: Log in to registry
        # This is where you will update the personal access token to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
        
      - name: Push Docker image
        run: |
          make push
